### PR TITLE
Candidates change also in the session if they change

### PR DESCRIPTION
**Pull request by gdujany**
Should solve a really rare corner case

### CODE REVIEW

**Comment by alexpearce** [comment]
Wouldn't it make more sense to `try` delete the `session['candidates']` key inside [`updateConfiguration`](https://github.com/gdujany/Condorcet/blob/ece45797db95981d7424a67b92f362a2e34549c6/Condorcet/__init__.py#L264)? Seems a more appropriate place, as the reason you need this check is because the list of candidates can change, and the change is performed inside `updateConfiguration`.

If you'd like to keep the code how you have it, it would be nice to add a comment explaining why the lines are there.

**Comment by gdujany** [comment]
mmm, if I del the session in the updateConfiguration it dels it only on the browser of the person who changes the candidates while like this if you change the candidates and I have the voting page open, if I refresh I should see the new candidates

**Comment by alexpearce** [comment]
Yes you're right, I hadn't that about it like that.

**Comment by gdujany** [comment]
btw, I noticed that I already delete the session['candidates'] inside the update otherwise testing would have been a mess

**Comment by alexpearce** [comment]
Mm yes. I suppose the only other place to put it would be to register a `before_request` method.

```
@app.before_request
def ensure_correct_candidates():
    """Ensure that the user session has a valid list of candidates."""
    if 'candidates' in session:
        if sorted(session['candidates']) != sorted(getConfig('OPTIONS')):
            del session['candidate']
```

But with documentation it doesn't matter where this goes.

**Pull request merged**
