### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by gdujany**
I am more or less done with adding new features to the admin page. 
Making it looks nicer could be a good idea even if not indispensable.
Before merging there is still to correct a lot of failing tests.

### CODE REVIEW

**Comment by alexpearce** [comment]
Will you also add tests for the new functionality?

**Comment by apuignav** [comment]
Hi,

As soon as I beat the trigger deadline (on Friday) I'll get on this.

Albert

**Comment by gdujany** [comment]
Now I forced the tests to pass by cheating: I did not manage to convince test_app to use as a config_db one created in a similar way to the vote(r)s db: I did manage to create one but then the methods drop_all and create_all do not seem to do their job in making the test use that db created (see branch test for example of things I tried without success). I thus for now cheated by creating the normal database before the tests that now pass. It is clear that however this is not the way to go. Alex, could you please have a look at it as you managed to have the other database to work? Without that missing peace I cannot write tests for the admin page (well, I could but keeping modifying the common db and not one created ad hoc).

**Comment by alexpearce** [comment]
@gdujany If this is still a problem I'll look in to it today.

**Comment by gdujany** [comment]
It would be great. In theory you should just make the test use a comfig database created ad hoc. In practice I didn't manage to do that.

Da:"Alex Pearce" notifications@github.com
Data:lun, 20 apr, 2015 alle 7:47
Oggetto:Re: [Condorcet] Admin (#16)

@gdujany If this is still a problem I'll look in to it today.

**Comment by alexpearce** [comment]
I've stared at things for a little while but I can't make much sense of the code anymore. Things seem to be intertwined in a way that makes testing very difficult.

**Comment by gdujany** [comment]
Yes, I guess that the problem is that I wanted to have load the new configuration immediately after having changed it so I read that part of the configuration from the database. At the same time I still wanted to keep the config file useful so I have a function to populate the config database from the content of config.py. That is useful while deploying the app the first time or resetting the config to the default values. 
Another design choice that maybe makes test hard is that all the admin related things (so playing with the admin database) is in updateConfig.py while the other databases are managed in manageDB.py.

**Pull request merged**
