### PR TITLE
Fixed bugs that broke website on asf

### PR DESCRIPTION
**Pull request by gdujany**
Let's try this method to ask for a pull request. 
I just fixed couple of bugs that made the website not working on asf.
btw it seems that app.route('/') is needed while for the other pages not. Maybe like this flask knows which page to show as first page but I don't know why.

### CODE REVIEW

**Comment by gdujany** [comment]
I just noticed that using url_for you have the real url with also "cgi-bin/homepage.fcg". 
When you put the url by hand that part is taken out by a directive in .htaccess but it seems that the tick do not work for url_for. Not that this is really an issue but if it's easy to modify...

**Comment by alexpearce** [comment]
Hmm OK, that sounds clumsy enough that I reckon there's probably some configuration somewhere that will make things work ‘as expected’. I'm taking a look now.

**Comment by alexpearce** [comment]
Just to check, I get a 500 error on this branch, is that expected?

**Comment by gdujany** [comment]
No, not expected at all, the website seems to work
https://gdujany.web.cern.ch/gdujany/Condorcet/ 
I may have missed something committing. In any case I just changed two lines and these had to be changed. I'll look a bit more into it if needed this afternoon.

**Comment by alexpearce** [comment]
OK, it might be something missing from the README then. I'll also have a look on my side.

**Comment by gdujany** [comment]
Have you changed the APPLICATION_ROOT?

**Comment by alexpearce** [comment]
Mm yes. Have given up for now, it's extremely unsatisfying to not be able to reproduce things, but as long as it's running somewhere then OK.

For the `fcgi` thing being used with `url_for`, could you try add snippet from [this page](http://flask.pocoo.org/docs/0.10/deploying/fastcgi/) to `homepage.fcgi`?

``` python
class ScriptNameStripper(object):
   def __init__(self, app):
       self.app = app

   def __call__(self, environ, start_response):
       environ['SCRIPT_NAME'] = ''
       return self.app(environ, start_response)

app = ScriptNameStripper(app)
```

**Comment by gdujany** [comment]
Now it should work. Can you confirm it? I still have to try the fcgi thing. I had a quick look and had errors so I prefer to do it in another branch

**Comment by gdujany** [comment]
Done the fcgi thing. The snippet needed a bit of massage:
environ['SCRIPT_NAME'] = environ['SCRIPT_NAME'].replace('cgi-bin/condorcet.fcgi','')

btw in environ['SCRIPT_NAME'] I used to have /gdujany/Condorcet/cgi-bin/condorcet.fcgi and now I have /gdujany/Condorcet/ that is the APPLICATION_ROOT! 
Maybe we can do without defining it in the config file that then need to be changed

**Comment by gdujany** [comment]
btw, along the same line, there is a way to not need to do change manually the line 
#!/bla/bla/venv/python to point to the correct virtual env?
Writing a little python script which does that should not be too long, does it make sense?

**Comment by alexpearce** [comment]
I know how to get the path to the current Python file, but you need the `#!` hashbang at the very beginning of the file, so I don't think there's a way that we can change it ‘on the fly’.

I don't quite follow your `fcgi` changes. So if you use `environ['SCRIPT_NAME'] = ''`, and then `APPLICATION_ROOT = '/gdujany/Condorcet'`, things don't work? But if use the `replace` stuff, it does? And `url_for` then works as expected, e.g. `url_for('root') == '/gdujany/Condorcet'`?

**Comment by alexpearce** [comment]
For me at the moment the link to `root` in the `<h1>` tag is linking to `https://gdujany.web.cern.ch/gdujany/Condorcet/cgi-bin/homepage.fcgi/gdujany/Condorcet/`.

**Pull request merged**
