### PR TITLE
Handle cases where only on DB is missing.

### PR DESCRIPTION
**Pull request by apuignav**
If one of the DB files was missing, when doing reset the script would fail.
I've written in a way so we can add further DBs in an easy way.

### CODE REVIEW

**Comment by apuignav** [comment]
I merge it myself since it's a simple fix.

**Comment by apuignav** [comment]
I merge it myself since it's a simple fix.

**Comment by gdujany** [comment]
Sure, just a doubt: when do you have only a database and not the other? I theory they should always go together because you keep tracks of who already voted in the voters database and you save the votes in the votes database, if you delate one and not the other or some votes are lost without the possibility for the voters to cast their vote again or someone can vote twice. 
I would thus add a print to highlight that something looks fishy, something along:
if os.path.exists(votes_file) ^ os.path.exists(voters_file): print 'One database existed and the other not, that looks fishy'

**Comment by apuignav** [comment]
I agree, but if you're resetting it doesn't matter, does it?

The idea of the reset is not only to recreate the dbs but also to fix the
system if there was a problem. I would not add any warnings here, you're
going to delete the files anyway if they exist.

Maybe it would be a good idea to add some kind of check feature, though, to
make sure the DBs are there and are reasonable before going to production
mode.

Albert

On Wed, Apr 8, 2015 at 11:51 AM, gdujany notifications@github.com wrote:

> Sure, just a doubt: when do you have only a database and not the other? I
> theory they should always go together because you keep tracks of who
> already voted in the voters database and you save the votes in the votes
> database, if you delate one and not the other or some votes are lost
> without the possibility for the voters to cast their vote again or someone
> can vote twice.
> I would thus add a print to highlight that something looks fishy,
> something along:
> if os.path.exists(votes_file) ^ os.path.exists(voters_file): print 'One
> database existed and the other not, that looks fishy'
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gdujany/Condorcet/pull/11#issuecomment-90865980.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by gdujany** [comment]
OK, that makes sense

**Pull request merged**
