### PR TITLE
Fuzzy match

### PR DESCRIPTION
**Pull request by gdujany**
Attempt to mitigate issue #23

### CODE REVIEW

**Comment by alexpearce** [comment]
This seems very brittle and difficult to maintain. Is this the solution we're going with?

**Comment by gdujany** [comment]
Not necessary, but it is a possibility:
- from my current understanding (I hope to be proven wrong) the only information we can retrieve from the membership database to identify a voter is his name and surname
- Name and surname may be different in the two databases

IF the above is true I can imagine only two solutions:
1. correct the membership database
2. be less fussy when comparing

The 1 a priory is the way to go even if it's a lot of work. I wanted to try 2

**Comment by betatim** [comment]
Fuzzy matching is a nice idea. I think people will worry though that someone who is not allowed to vote will end up being allowed to vote. Can we think of a good way to estimate the probability for that happening? Does glance contain the authorlist of ATLAS/CMS? If so we could see if any of those would be classed as a "match"?

**Comment by gdujany** [comment]
I did a check with a csv file I got form Atlas' Glance and I obtained 22 truly different matches for 5071 attempts (~0.4%). There were also 13 true matches like Antonio Di Domenico.
One should also consider that people not in the z5 group cannot see the voting page irrespective if they are in the author list or not.

**Pull request closed without merging**
